#公共配置
server:
  port: 9330
  tomcat:
    uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #模板引擎配置
  freemarker:
    cache: false
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      auto_import: common/common.ftl as com
      datetime_format: yyyy-MM-dd
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    request-context-attribute: request
    prefix:
    suffix: .ftl
    template-loader-path: classpath:/templates/

  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  application:
    name: manage
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 1000
  password:

#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mybatis/*Mapper.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.yangy.manage.entity

#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #    logic-delete-value: 1
#    #    logic-not-delete-value: 0
#    #自定义填充策略接口实现
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

---
#开发环境配置
server:
  #端口
  port: 9330
spring:
  profiles: dev
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9230/eureka
---
#测试环境配置
server:
  #端口
  port: 8085
spring:
  profiles: test
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root

---
#生产环境配置
server:
  #端口
  port: 8080
spring:
  profiles: pro
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root








